### ISSUE TITLE
ParallelMap  and List

### ISSUE THREAD

**Issue by Pimikov** [FormTracer/FormTracer#1] opened 2017-04-09 00:23 UTC
There are two issues I found working  on Mathematica 11.0 for Linux 64

One is related to Lists
In= FormTrace[ {fvd[p, mu] fvd[q, mu], fvd[p, mu] fvd[q, mu]}]
Out= 2 spd[p, q]

An other to Parallel Mapping for long lists. While for short lists it's working well.
In:= list = fvd[p, mu] fvd[q, mu] Range[1000];
In:= ParallelMap[FormTrace, list]
(kernel 1) DeleteFile::fdnfnd :  Directory or file /tmp/runform_2017-04-09-03-13-23.401708.frm not found.
(kernel 1) DeleteFile::fdnfnd :  Directory or file /tmp/runform_2017-04-09-03-13-24.730253.frm not found.
(kernel 1) ImportFormResult::noformoutput :  An unknown FORM error occured!
No FORM output was generated.
(kernel 1) DeleteFile::fdnfnd :  Directory or file /tmp/runform_2017-04-09-03-13-27.359470.frm not found.
(kernel 3) DeleteFile::fdnfnd :  Directory or file /tmp/runform_2017-04-09-03-13-28.447646.frm not found.
(kernel 3) ImportFormResult::noformoutput :  An unknown FORM error occured!
No FORM output was generated.
Out= $Aborted

**Comment by antoncyrol** [comment] 2017-04-09 08:43
Dear Pimikov,
thank you for reporting this to us!

Concerning the first issue: I guess you expected `{spd[p,q], spd[p,q]}` as outcome. However, this behavior is intended, lists of traces are summed to benefit from possible cancellations, as described in the help page of `FormTrace`. The idea is that multiple diagrams are often more efficiently described in one sum. I see that this might be confusing as it is different from most internal Mathematica functions but one can always simply use Map, as you did, if one needs individual expressions.

Concerning the second issue: Although I cannot yet reproduce this (also working with Mathematica 11.0 / Linux 64), I think I know what's going wrong: The temporary files are named with a time stamp (e.g. 2017-04-09-03-13-27.359470). If you have many many files, the time stamps may coincide and collide. We will fix this!

Best,
Anton

**Comment by antoncyrol** [comment] 2017-04-21 11:00
This should be fixed now.

**Closed as completed** 2017-06-08 10:20 UTC
